dist: xenial
sudo: false
arch: s390x
language: cpp

cache: ccache

addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.icinga.com/ubuntu icinga-xenial main'
        key_url: 'https://packages.icinga.com/icinga.key'
    packages:
      - vim
      - git
      - locales
      - cmake
      - make
      - build-essential
      - libssl-dev
      - libboost-all-dev
      - bison
      - flex
      - libmysqlclient-dev
      - libpq-dev
      - libyajl-dev
      - libedit-dev
      - monitoring-plugins
      - php-intl
      - php-imagick
      - mysql-server
      - mysql-client
      - libapache2-mod-php
      - apache2
      - php-fpm
      - mailutils
      - php-gd
      - php-pgsql
      - php-xml
      - php-curl
      - php-mysql
      - php-ldap
      - php-mockery
      - php-mbstring
      - phpunit
      - php
      - wget
before_script:
  - arch=$(uname -m)
  - mkdir build
  - cd build
  - >
    cmake ..
    -DCMAKE_BUILD_TYPE=Debug
    -DICINGA2_UNITY_BUILD=Off
    -DCMAKE_INSTALL_PREFIX=/tmp/icinga2
    -DICINGA2_PLUGINDIR=/tmp/icinga2/sbin
    -DBoost_NO_BOOST_CMAKE=TRUE
    -DBoost_NO_SYSTEM_PATHS=TRUE
    -DBOOST_LIBRARYDIR=/usr/lib/${arch}-linux-gnu/icinga-boost
    -DBOOST_INCLUDEDIR=/usr/include/icinga-boost
    -DCMAKE_INSTALL_RPATH=/usr/lib/${arch}-linux-gnu/icinga-boost

script:
  - make
  - make test
  - make install
  - /tmp/icinga2/sbin/icinga2 --version
  - /tmp/icinga2/sbin/icinga2 daemon -C -DRunAsUser=$(id -u -n) -DRunAsGroup=$(id -g -n)
  
branches:
  only:
  - s390x-travis-test
  
